config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "my_devise/registrations" }
  root to: 'trainers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :trainers, :customers, only: [ :index, :show, :edit, :update, :destroy ] do
      resources :requests, only: [ :index, :show, :new, :create, :destroy ]
    end

    resources :sportlers, only: [ :index, :new, :create, :destroy ] do
      resources :sports, only: [ :index, :new, :create, :destroy ]
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :trainers, through: :requests
  has_many :requests

  # validates :email, format: { with: /\A.*@.*\.com\z/ }, uniqueness: true


end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :customer
  belongs_to :trainer
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :sportlers
  has_many :users, through: :sportlers
end

app/models/sportler.rb
class Sportler < ApplicationRecord
  belongs_to :user
  has_many :sports
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  belongs_to :user
  has_many :customers, through: :requests
  has_many :requests
  accepts_nested_attributes_for :requests

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :trainer
  has_one :customer
  has_one :sportler
  has_many :sports, through: :sportler

  validates :role, presence: true, inclusion: { in: %w(customer trainer) }

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def set_current_user
    User.current = current_user
  end

  def after_sign_in_path_for(resource)
    if resource.customer
      trainer_request_path(resource.customer.requests.last.trainer.id, resource.customer.requests.last.id)
    else
      root_path
    end
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_customer, only: %i[show edit update]

  def index
    @user = current_user
    @customers = Customer.all
  end

  def show
  end

  def new
    @customer = Customer.new
    @customer.user = current_user
  end

  def create
    if User.create
      @user     = User.find(params[:id])
      @customer = User.create(@user)
      @custome.save
    end
  end

  def edit
  end

  def update
    @customer.update(params[:customer])
    if @customer.update(customer_params)
      redirect_to customer_path(@customer)
    else
      render :edit
    end
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit( :name, :email, :description, :picture)
  end

end

app/controllers/my_devise/registrations_controller.rb
class MyDevise::RegistrationsController < Devise::RegistrationsController

  def create
    super
    if resource.save
      @customer         = Customer.new
      @customer.user_id = resource.id
      @customer.email = resource.email
      @customer.save
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  before_action :set_current_user

  def show
    @trainer = Trainer.find(params[:trainer_id])
    @request = Request.find(params[:id])
    @trainer = @request.trainer
  end

  def new
    @trainer = Trainer.find(params[:trainer_id])
    @request = Request.new
  end

  def create
    @trainer = Trainer.find(params[:trainer_id])
    @request = Request.create(request_params)
    @request.customer_id = current_user.customer.id
    @request.trainer_id = @trainer.id
    @request.save
    redirect_to trainer_request_path(@request.trainer_id, @request)
  end

  private

  def  request_params
    params.require(:request).permit(:customer_id, :trainer_id, :state)
  end

end

app/controllers/sportlers_controller.rb
class SportlersController < ApplicationController
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @user = current_user
    @trainers = Trainer.all
  end

  def show
    @trainer = Trainer.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    @user.save
  end

  private

  def user_params
    params.require(:user).permit(%i[email role])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/index.html.haml
- @customers.each do |customer|
  = link_to customer.name, user_customer_path(customer.user_id, customer.id)
  = customer.email

app/views/customers/show.html.haml
%ul
  = @customer.name
  = @customer.email

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/requests/index.html.haml
= @requests

app/views/requests/show.html.haml
.center-screen
  = "Great! #{@request.trainer.name} got your Message and will get  back to you within 48 hours "

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-left navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
            <%= link_to 'Your Profile', customer_path(current_user.customer.id) %>
        <% else %>
          <!-- Login link (when logged out) -->
          <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>
        </li>
        <li><a href="#">Training Advisor Location</a></li>
        <li><a href="#">Invite Friends</a></li>
      </ul>
    </div>
  </div>
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= 'PT SPORTS APP' %>
  <% end %>
</div>

app/views/trainers/index.html.haml
.small-12.columns

  - @trainers.each do |trainer|
    %ul
      = link_to trainer.name, trainer_path(trainer)
      = trainer.city
      = trainer.sport_type

app/views/trainers/show.html.haml
%ul
  = @trainer.name
  = @trainer.sport_type
  = @trainer.price
  = @trainer.training_location
  = @trainer.city
  = @trainer.availiability

%ul
  = simple_form_for Request.new, url: trainer_requests_path(@trainer) do |f|
    = f.input :trainer_id, as: :hidden, input_html: { value: @trainer }
    = f.submit 'Book', class: 'btn-success'